### PR TITLE
Update LICENSE to something more rational

### PR DESCRIPTION
**Pull request by JakeCataford**
This pr does things to the license. Just merge dont look.

### CODE REVIEW

**Comment by JakeCataford** [comment]
please

**Comment by maximebedard** [comment]
👍

**Comment by JakeCataford** [comment]
No actually please review this

**Comment by JakeCataford** [comment]
please

**Comment by maximebedard** [comment]
no

**Comment by JakeCataford** [comment]
please

**Comment by JakeCataford** [comment]
pls review @maximebedard

**Pull request closed without merging**
